#!/usr/bin/env bash
# wg-server-deploy.sh — WireGuard server deployment for Ubuntu 22.04 (NAT internet breakout).
#
# What it does:
# - Installs packages (wireguard, iptables)
# - Enables IPv4/IPv6 forwarding (sysctl)
# - Generates server keypair in /etc/wireguard/keys/
# - Writes /etc/wireguard/<iface>.conf with Address=<server-ip>/<prefix>, ListenPort, NAT (MASQUERADE)
# - Enables + starts wg-quick@<iface>
# - If UFW is active: allows <port>/udp
# - Stores client defaults:
#     /etc/wireguard/<iface>.endpoint         (host:port)
#     /etc/wireguard/<iface>.dns              (DNS for clients)
#     /etc/wireguard/<iface>.client-allowedips (AllowedIPs on clients; default full-tunnel)
#
# Usage (your scenario):
#   sudo bash ./wg-server-deploy.sh deploy \
#     --iface wg0 --subnet 10.27.255.0/24 --server-ip 10.27.255.1 \
#     --port 51820 --endpoint vmx-prt-vpn-04.ddnsfree.com \
#     --dns 1.1.1.1
#
# Notes:
# - This script configures NAT so clients reach the internet ONLY via the server (full tunnel requires client AllowedIPs=0.0.0.0/0,::/0).
# - NAT uses iptables; Ubuntu 22.04 typically uses the iptables-nft backend, which is fine.

set -euo pipefail
umask 077

log() { echo "[$(date -Is)] $*" >&2; }
die() { echo "ERROR: $*" >&2; exit 1; }

need_root() { [[ ${EUID:-$(id -u)} -eq 0 ]] || die "Run as root (sudo)."; }
have_cmd() { command -v "$1" >/dev/null 2>&1; }

conf_path() { echo "/etc/wireguard/${IFACE}.conf"; }
defaults_dir() { echo "/etc/wireguard"; }
keydir="/etc/wireguard/keys"

backup_file() {
  local f="$1"
  [[ -f "$f" ]] || return 0
  cp -a "$f" "${f}.bak.$(date +%Y%m%d%H%M%S)"
}

detect_default_iface() {
  ip route show default 0.0.0.0/0 2>/dev/null | awk '/default/ {print $5; exit}'
}

validate_cidr_and_ip() {
  python3 - <<PY
import ipaddress, sys
subnet = "${SUBNET}"
srv_ip = "${SERVER_IP}"
try:
    net = ipaddress.ip_network(subnet, strict=False)
except Exception as e:
    sys.exit(f"Invalid --subnet '{subnet}': {e}")
try:
    ip = ipaddress.ip_address(srv_ip)
except Exception as e:
    sys.exit(f"Invalid --server-ip '{srv_ip}': {e}")
if ip.version != net.version:
    sys.exit(f"--server-ip {ip} and --subnet {net} are different IP versions.")
if ip not in net:
    sys.exit(f"--server-ip {ip} is not inside --subnet {net}.")
# prefix length
print(net.prefixlen)
PY
}

validate_port() {
  [[ "$PORT" =~ ^[0-9]+$ ]] || die "Invalid --port '$PORT'"
  (( PORT >= 1 && PORT <= 65535 )) || die "Invalid --port '$PORT' (must be 1..65535)"
}

install_packages() {
  export DEBIAN_FRONTEND=noninteractive
  apt-get update -y
  apt-get install -y wireguard wireguard-tools iptables iproute2
}

enable_forwarding() {
  local sysctl_file="/etc/sysctl.d/99-wireguard-forward.conf"
  cat >"$sysctl_file" <<'EOF'
net.ipv4.ip_forward=1
net.ipv6.conf.all.forwarding=1
EOF
  sysctl --system >/dev/null
}

gen_server_keys() {
  install -d -m 700 "$keydir"
  local priv="${keydir}/server.key"
  local pub="${keydir}/server.pub"

  if [[ ! -f "$priv" ]]; then
    wg genkey | tee "$priv" >/dev/null
    chmod 600 "$priv"
  fi
  if [[ ! -f "$pub" ]]; then
    wg pubkey <"$priv" >"$pub"
    chmod 600 "$pub"
  fi
}

write_server_conf() {
  install -d -m 700 /etc/wireguard
  local conf; conf="$(conf_path)"

  if [[ -f "$conf" && "$FORCE" -ne 1 ]]; then
    die "Config already exists at $conf. Re-run with --force to overwrite (a backup will be made)."
  fi

  backup_file "$conf"

  local priv="${keydir}/server.key"
  [[ -f "$priv" ]] || die "Missing server private key at $priv"

  # Use the WG subnet as source subnet for NAT
  local src_subnet="$SUBNET"

  cat >"$conf" <<EOF
# Generated by wg-server-deploy.sh on $(date -Is)

[Interface]
Address = ${SERVER_IP}/${PREFIXLEN}
ListenPort = ${PORT}
PrivateKey = $(cat "$priv")
SaveConfig = false

# NAT internet breakout for VPN clients:
PostUp   = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -s ${src_subnet} -o ${PUBLIC_IFACE} -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -s ${src_subnet} -o ${PUBLIC_IFACE} -j MASQUERADE
EOF

  chmod 600 "$conf"
}

open_firewall_if_ufw() {
  if have_cmd ufw && ufw status >/dev/null 2>&1; then
    if ufw status | grep -qi "Status: active"; then
      ufw allow "${PORT}/udp" >/dev/null || true
    fi
  fi
}

write_client_defaults() {
  # Endpoint stored as host:port
  local ep="${ENDPOINT_HOST}:${PORT}"
  echo -n "$ep" >"$(defaults_dir)/${IFACE}.endpoint"
  echo -n "$DNS" >"$(defaults_dir)/${IFACE}.dns"
  echo -n "$CLIENT_ALLOWEDIPS" >"$(defaults_dir)/${IFACE}.client-allowedips"
  chmod 600 "$(defaults_dir)/${IFACE}.endpoint" "$(defaults_dir)/${IFACE}.dns" "$(defaults_dir)/${IFACE}.client-allowedips"
}

start_service() {
  systemctl enable --now "wg-quick@${IFACE}" >/dev/null
}

status() {
  echo "Config: $(conf_path)"
  echo "Server public key: $(cat "${keydir}/server.pub" 2>/dev/null || true)"
  echo
  systemctl status "wg-quick@${IFACE}" --no-pager || true
  echo
  wg show "${IFACE}" || true
}

usage() {
  cat <<'EOF'
Usage:
  sudo bash ./wg-server-deploy.sh deploy [options]
  sudo bash ./wg-server-deploy.sh status --iface wg0

Commands:
  deploy    Install + configure WireGuard server (NAT breakout)
  status    Show service + wg status

Deploy options:
  --iface <wg0>           WireGuard interface name (default: wg0)
  --subnet <CIDR>         VPN subnet for clients (default: 10.27.255.0/24)
  --server-ip <IP>        Server VPN IP inside subnet (default: 10.27.255.1)
  --port <51820>          Listen UDP port (default: 51820)
  --public-iface <eth0>   Outbound interface used for NAT (default: auto-detect)
  --endpoint <dns-or-ip>  Public DNS/IP clients will use (stored as host:port). REQUIRED for deploy.
  --dns <ip>              DNS pushed to clients by management scripts (default: 1.1.1.1)
  --client-allowedips <..> AllowedIPs in client configs (default: 0.0.0.0/0,::/0)
  --force                 Overwrite existing /etc/wireguard/<iface>.conf (backup first)

Example (your scenario):
  sudo bash ./wg-server-deploy.sh deploy \
    --iface wg0 --subnet 10.27.255.0/24 --server-ip 10.27.255.1 \
    --port 51820 --endpoint vmx-prt-vpn-04.ddnsfree.com --dns 1.1.1.1
EOF
}

# Defaults
IFACE="wg0"
SUBNET="10.27.255.0/24"
SERVER_IP="10.27.255.1"
PORT="51820"
PUBLIC_IFACE=""
ENDPOINT_HOST=""
DNS="1.1.1.1"
CLIENT_ALLOWEDIPS="0.0.0.0/0,::/0"
FORCE=0

main() {
  need_root
  [[ $# -ge 1 ]] || { usage; exit 1; }

  local cmd="$1"; shift

  case "$cmd" in
    deploy)
      while [[ $# -gt 0 ]]; do
        case "$1" in
          --iface) IFACE="$2"; shift 2 ;;
          --subnet) SUBNET="$2"; shift 2 ;;
          --server-ip) SERVER_IP="$2"; shift 2 ;;
          --port) PORT="$2"; shift 2 ;;
          --public-iface) PUBLIC_IFACE="$2"; shift 2 ;;
          --endpoint) ENDPOINT_HOST="$2"; shift 2 ;;
          --dns) DNS="$2"; shift 2 ;;
          --client-allowedips) CLIENT_ALLOWEDIPS="$2"; shift 2 ;;
          --force) FORCE=1; shift 1 ;;
          -h|--help) usage; exit 0 ;;
          *) die "Unknown arg: $1" ;;
        esac
      done

      [[ -n "$ENDPOINT_HOST" ]] || die "--endpoint is required (DNS name or public IP)."
      [[ -n "$PUBLIC_IFACE" ]] || PUBLIC_IFACE="$(detect_default_iface)"
      [[ -n "$PUBLIC_IFACE" ]] || die "Could not auto-detect --public-iface; set it explicitly."

      validate_port
      PREFIXLEN="$(validate_cidr_and_ip | tail -n1)"

      log "Installing packages..."
      install_packages

      log "Enabling forwarding..."
      enable_forwarding

      log "Generating server keys (if missing)..."
      gen_server_keys

      log "Writing server config: $(conf_path)"
      write_server_conf

      log "Opening firewall (ufw) if active..."
      open_firewall_if_ufw

      log "Writing client defaults..."
      write_client_defaults

      log "Starting service wg-quick@${IFACE} ..."
      start_service

      echo
      echo "OK"
      echo "Interface: ${IFACE}"
      echo "WG subnet:  ${SUBNET}"
      echo "WG GW:      ${SERVER_IP}"
      echo "Endpoint:   ${ENDPOINT_HOST}:${PORT}"
      echo "Server pub: $(cat "${keydir}/server.pub")"
      echo
      echo "Next: add peers using your management script (example):"
      echo "  sudo bash ./wg-deploy2.sh add alice --iface ${IFACE} --endpoint ${ENDPOINT_HOST}:${PORT} --ip4 10.27.255.2 --client-allowed \"0.0.0.0/0,::/0\" --dns \"${DNS}\""
      ;;

    status)
      while [[ $# -gt 0 ]]; do
        case "$1" in
          --iface) IFACE="$2"; shift 2 ;;
          -h|--help) usage; exit 0 ;;
          *) die "Unknown arg: $1" ;;
        esac
      done
      status
      ;;

    -h|--help)
      usage
      ;;

    *)
      usage
      exit 1
      ;;
  esac
}

main "$@"
